### ISSUE TITLE
How to add custom script to emuelec? 

### ISSUE THREAD

**Issue by farhanito** [shantigilbert/EmuELEC#21]
Is it possible to add custom script to "RetroPie collection" tab?

**Comment by shantigilbert** [comment]
On the standalone yes, I am not sure on the add-on

But you can see the path in es_systems.cfg is "/emuelec/scripts/modules" 
So just drop whatever .sh file you want there and it should work.

**Comment by farhanito** [comment]
Thanks.

Yes, I am using the standalone. 
The script shows up, but not working. 

Here's what I am trying to do.. 
https://discourse.coreelec.org/t/sx05re-retro-emulation-kodi-addon-for-coreelec-released-for-testing/3203/433?u=farhanito

Script works as expected when executed from SSH.

**Comment by shantigilbert** [comment]
What happens when you select it in ES? 
Is there any info on /storage/.emulationstation/es_log.txt 

what happens if you use this script instead?

```
#!/bin/bash

source /emuelec/scripts/env.sh
source "$scriptdir/scriptmodules/supplementary/esthemes.sh"
rp_registerAllModules

joy2keyStart

mount -o rw,remount /flash
mv /flash/boot.ini /flash/boot.ini.emu
read -n 1 -s -r -p "Press any key to reboot"
reboot
```

**Comment by farhanito** [comment]
Ah, sorry.. It was Permission issue.

And your script is perfect. 

Thanks again.

**Comment by shantigilbert** [comment]
Also, just to be safe, you might want to add a "sync" command before rebooting.

**Comment by shantigilbert** [comment]
Custom scripts should now go into "/emuelec/scripts/custom_scripts/"
