### ISSUE TITLE
About PPSSPP SDL

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/EmuELEC#25]
hello, there. Long time no see, hope you are doing well. I was wondering if we can use the hotkey to quit ppssppa (ppsspp sdl) with ES? maybe like press 'hotkey + start'?

**Comment by WXDFever** [comment]
update: I mean quit ppssppa to ES, not quit to the menu of ppssppa. Thanks in advance

**Comment by WXDFever** [comment]
update: I mean quit ppssppa to ES, not quit to the menu of ppssppa. Thanks in advance

**Comment by shantigilbert** [comment]
Not that I know off, and this is not a bug, please only open issues if they are bugs, else use Discord to discuss stuff like this https://discord.gg/QqGYBzG
