### ISSUE TITLE
How to connect my Bluetooth gamepade

### ISSUE THREAD

**Issue by kero990** [shantigilbert/EmuELEC#36]
In the original sx05re, there is a kodi to assist in connecting to a Bluetooth device. Now kodi has been deleted, is there no connection option for the Bluetooth device? The Ps3 gamepad can be connected to Bluetooth with a data cable connection first. What about other Bluetooth gamepads?

PS:Above from Google Translate, I hope you can understand

**Comment by shantigilbert** [comment]
https://github.com/shantigilbert/EmuELEC/wiki/Bluetooth

**Comment by shantigilbert** [comment]
No answer, so closing this issue
