### ISSUE TITLE
Can't connect to XBOX ONE bluetooth controller

### ISSUE THREAD

**Issue by shulthz** [shantigilbert/EmuELEC#37]
Can't connect to XBOX ONE bluetooth controller with 'bluetoothctl'.

`Failed to connect: org.bluez.Error.Failed`

PHICOMM N1 
S905D

**Comment by shantigilbert** [comment]
Please check the wiki for Bluetooth instructions. I have one question how did you manage to boot up the phincomm? #27 is having problems with the same device.

**Comment by shulthz** [comment]
> 
> 
> Please check the wiki for Bluetooth instructions. I have one question how did you manage to boot up the phicomm? #27 is having problems with the same device.

I think he can get the answer from below：
https://right.com.cn/forum/thread-323198-1-1.html

I followed the wiki for Bluetooth instructions，but failled.

**Comment by shantigilbert** [comment]
Can you try with the new version? on the main menu under controllers you should see an option to connect to Bluetooth

**Comment by shantigilbert** [comment]
No reply for 10 days, closing issue. Feel free to reopen it again if the problem is still there

**Comment by shulthz** [comment]
It's very hard to download the the new release in China, i will try it when dowload it~~!
