### ISSUE TITLE
ES freezes and crashes in the gamelist view

### ISSUE THREAD

**Issue by hzio** [shantigilbert/EmuELEC#45]
Hi @shantigilbert recently I found a boring bug, there are 2000+ games in my arcade system, **ES freezes and crashes** after holding the joypad's `DOWN` button for about 30 seconds in gamelist view, this issue appears in both video UI mode and detail UI mode, please help :(

**Comment by shantigilbert** [comment]
Cannot reproduce on 3 different boxes, with a mame folder of 6000+ games
