### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Power535** [shantigilbert/EmuELEC#47]
How add supported project ?
https://github.com/malaterre/OpenELEC.tv/tree/ci20-devel/projects/ci20
or please add supported project
Need help

**Comment by shantigilbert** [comment]
Emuelec is only for Amlogic devices, sorry

**Comment by Power535** [comment]
Your projects Amlogic and other
How add supported project , need only copy project or need configure ?
If possible help
I want add device and try compile

**Comment by Power535** [comment]
Thank you for your message
