### ISSUE TITLE
CVBS not working on X96 s905W

### ISSUE THREAD

**Issue by edneyhelene** [shantigilbert/EmuELEC#49]
Hello, i cant make it work.

it boots up, then i can see the emuelec logo on the old tv, and then black screen.
I tried to add EE_VIDEO_MODE file to the sdcard on the same folder as dtb.img but nothing changes. 

This tv supports 480cvbs video only via composite cable.
Android tv works ok on it, i was even using atvxperience.
I really need to make it work on this old tv, its a must for me, i'm desperate.

The box is the X96 S905X with 2gb ram and 16gb rom.

Please help?

**Comment by edneyhelene** [comment]
Solution found!
Steps to fix the problem:

Open nautilus as root on linux.
Navigate to STORAGE/.config/emulationstation/ es_settings.cfg
and replace the resolution to match your tv resolution:

in my case it was <string name="EmuELEC_VIDEO_MODE" value="480cvbs" /> 
inserted 480cvbs and it works!

Problem closed

**Comment by shantigilbert** [comment]
This is now fixed on latest commits, EE_VIDEO_MODE takes priority

**Comment by varma86** [comment]
Set 2160p60hz and it worked. Might be a incompatibility with my Hitachi TV.
Very strange because CoreElec works pretty well in 1080p too. Android too is set to 1080p.
I hope you will investigate. Maybe I could help with some log files, if you instruct me how to.

**Comment by Sidordroid** [comment]
EE_VIDEO_MODE and what folder should this file be put in? And what should be written in it?I guess 480cvbs 576cvbs?
